repos:
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
    - id: isort

